FROM simonsdave/xenial-dev-env:%DEV_ENV_VERSION%

LABEL maintainer="Dave Simons"

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /tmp/package
ADD package.tar.gz /tmp/package/.

RUN cd /tmp/$PACKAGE && pip install --requirement "requirements.txt"

RUN rm -rf "/tmp/package"

ENV DEBIAN_FRONTEND newt
